name: Deploy

on: workflow_dispatch

jobs:
  deploy:
    runs-on: ubuntu-latest
    name: Deploy
    steps:
      - uses: actions/checkout@v4
      - name: Deploy
        uses: cloudflare/wrangler-action@v3
        env:
          D1_NAME: ${{ vars.D1_NAME }}
          D1_ID: ${{ vars.D1_ID }}
          PERSIST: ${{ vars.PERSIST }}
          CUSTOM_DOMAIN: ${{ vars.CUSTOM_DOMAIN }}
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          preCommands: ./prepare.sh
